language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: practica-isi-citr
  api_key:
    secure: Rr+o5/0nCzIy8l+OxehU1WdZ8IzjDS4Ll1zGHiou5FYu1euBwhyN9EUQrynJnSOlgUkXvzP5SHwhtREqRi9giZDa/6xiEASo8QGbtFmleNW5hrovEgnocHnOTtaC831Js25VBU2qa1Apde4xhr3sY4a/9LJCkJES68HwhPKOjzBS8fnzrJ14bvNcBvDmil2KacD8HoEAMaok1SQr8fPrzSizL3RGKJNMX4yCGVe5tfR2ucndLeG08kSMEz7vFQcNS4PfwkJaEJ/fxM0TKJYjEGjz7cTeiCdyS7gPwovzCu2Q6ZyL/IqQFx0eQDXctPc0P3Cufb3QHWNpFU6Mw5l6K/uLcXoT5NBu2+Tgxo8qhXflu168Aq0rLb4hSieRXUaZksYG8FWN/eaDllRgVtPLU5kc8G90/xjVM32HIwrlD7S9amG+mhhkBxUgxilsN5268htKO5Wq3BX2sbB6waylkIfSxp1fuRuwEX7Q/5sSr5Zp0/HyojwCexCJAsEuBH4Vmo5u2f5fgzwFfVE572tMkyvyjvDLgvd53km+fLleMI1j+LfhNz5YwWrduHkQpYMsegamfhwojyjgmMPJQVegmwLlZRVGU2thmbqf4L6HxfXGUIIU3OTKgSaW9ZqaKafnU+gIoH873H97gaLdkQBrZIDKzgXWMvaZE1X2w0RYUYo=
