language: java
deploy:
  skip_cleanup: true
  provider: heroku
  app: p-final-isi
  api_key:
    secure: YtZslOhEWqRta7cbgIH7cm9p3syD7LR/v5wTylRbMlXXhHG+XljbfRoCXy3tGl3E94jRViCkpI+Kfd38+fn+6JnsPv+uOZU+PYtWA+YchwvMzXGk5SollFB+va3O7piXBz+JHTbw0tD5Lju0ZFxk0S3426HFg94orI01/jGKrBgp0iBYRVchq3ww5YT07DLjFnCWkSO9KND0SWWgikaZZdx3ZkgXTs+qZs0jt7VfTzW0GKLXZD6RoT2Nl/UzHmxwACZraD1MVpbinybdlhyzQQIxvtIJDjda7zlfRFDBb5Ob2KG1DSZPC0b1TbwQjd7wfP8jti6QbBCEU4rlZvR2xEDELgkc+hKdKPJgwFfLbLLBdAC3NqjEuNhVTmFHLi3Xm4ByK4kPI5ZkwJDoKlS4pU8gozDUhgrj6Cs0TV12WSufmCVUIHP5EG3sQEzHbLJ6Z/tJH8wq0s4IkBmFiP1mSj0jN5cNuKD0/uq216NU7Qgrw36KFq0AsBSifBOVIWFzj72DlcfoPP0hv5L2mOYd3nuyKwSIN8TF9kRIZXQx7Ver+TltFWowdLCdUDtGUxinFV5T/j1Xpw2BT8eRDsGeY/XWx+hNTwmYB9MQxrpCbmpJIX5JxcS2IoU2ECyShOgaWzxPZmd011AglHOexalTjq0orwoLnMrAd+YoTVCQwjU=
